# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: efcore-migration-script-generator-task@1
  displayName: 'Generate Migrations Script'
  inputs:
    projectpath: 'Backend/E-Forester.Infrastructure/E-Forester.Infrastructure.csproj'
    databasecontexts: 'E_ForesterDbContext'
    startupprojectpath: 'Backend/E-Forester.API/E-Forester.API.csproj'
    targetfolder: '$(build.artifactstagingdirectory)/migrations'
    build: true
    installdependencies: true
    eftoolversion: '5.0.12'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: "Publish"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'